# Generated by Django 5.2.6 on 2025-09-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PG", "Pending"), ("PD", "Paid")], max_length=2
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PT", "Payment"), ("F", "Fine")], max_length=2
                    ),
                ),
                ("session_url", models.URLField()),
                ("session_id", models.TextField()),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
